insert into APP_USER(ID,FIRST_NAME,LAST_NAME,USER_NAME,STATUS) values(2000,'SRINIVAS','GUDIPATI','SGUDIPATI','ACTIVE');
insert into APP_USER(ID,FIRST_NAME,LAST_NAME,USER_NAME,STATUS) values(2001,'RAM','V','VRAM','ACTIVE');
insert into APP_USER(ID,FIRST_NAME,LAST_NAME,USER_NAME,STATUS) values(2002,'LAXMAN','G','GLAXMAN','ACTIVE');